export const Product_constants = {
    GET_PRODUCT_SLUG: 'GET_PRODUCT_SLUG',

    
    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
}

export const Page_constants = {
    
    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',


}

export const authConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_REQUEST : "LOGOUT_REQUEST",
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    LOGOUT_FAILURE : "LOGOUT_FAILURE",
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILURE : "SIGNUP_FAILURE",
}

export const cartConstants = {
    ADD_TO_CART_REQUEST : "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS : "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE : "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART"
}

export const userAddressConstants = {
    GET_USER_ADDRESS_REQUEST : "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS:"GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE"

}
export const orderConstants = {
    ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
    ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
    ADD_ORDER_FAILURE: "ADD_ORDER_FAILURE",
    
    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAILURE: "GET_ORDER_FAILURE",

    //for invoice constants
    GET_INVOICE_ORDER_REQUEST: "GET_INVOICE_ORDER_REQUEST",
    GET_INVOICE_ORDER_SUCCESS: "GET_INVOICE_ORDER_SUCCESS",
    GET_INVOICE_ORDER_FAILURE: "GET_INVOICE_ORDER_FAILURE",
}